---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-map
data:
  ENV : PRODUCTION
---
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: frontend
spec:
  containers:
  - name: frontend-env
    image: sameerat8/angularfrontend-k8s-env:1.1
    ports:
    - containerPort : 8080
    envFrom:
      - configMapRef:
          name: test-config-map
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/env_token.js > /usr/share/nginx/html/env.js"]